version: 1.0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./VideoGameStore/VideoGameStore.sln
build:
  project: ./VideoGameStore/VideoGameStore.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
services:
  - mssql2016

environment:
  COVERALLS_REPO_TOKEN:
    secure: Sx0bGuXkGeKfe47s9KRRzPHSBVQLzGVkE

after_test: 
        - VideoGameStore\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"VideoGameStore\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single VideoGameStore\VideoGameStore.Web.Testss\bin\Debug\VideoGameStore.Web.Tests.dll" -output:cover.xml

        - VideoGameStore\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml
